-- EXERCISE 1 --
-- PROBLEM 1 --
select * from employees where JOB_ID IN (select JOB_IDENT from jobs);
-- PROBLEM 2 --
SELECT * FROM EMPLOYEES WHERE JOB_ID IN (SELECT JOB_IDENT FROM JOBS WHERE JOB_TITLE='Jr. Designer');
-- PROBLEM 3 --
SELECT * FROM JOBS WHERE JOB_IDENT IN (SELECT JOB_ID FROM EMPLOYEES WHERE SALARY > 70000);
-- PROBLEM 4 --
SELECT * FROM JOBS WHERE JOB_IDENT IN (SELECT JOB_ID FROM EMPLOYEES WHERE YEAR(B_DATE) > 1976);
-- PROBLEM 5 --
SELECT * FROM JOBS WHERE JOB_IDENT IN (SELECT JOB_ID FROM EMPLOYEES WHERE SEX = 'F' AND YEAR(B_DATE) > 1976);
-- EXERCISE 2--
-- PROBLEM 1 --
SELECT * FROM EMPLOYEES, JOBS;
-- PROBLEM 2 --
SELECT * FROM EMPLOYEES, JOBS WHERE EMPLOYEES.JOB_ID=JOBS.JOB_IDENT;
-- PROBLEM 3 --
SELECT * FROM EMPLOYEES E, JOBS J WHERE E.JOB_ID=J.JOB_IDENT;
-- PROBLEM 4 --
SELECT EMP_ID, F_NAME, L_NAME, JOB_TITLE FROM EMPLOYEES E, JOBS J WHERE E.JOB_ID=J.JOB_IDENT;
-- PROBLEM 5 --
SELECT E.EMP_ID, E.F_NAME, E.L_NAME, J.JOB_TITLE FROM EMPLOYEES E, JOBS J WHERE E.JOB_ID=J.JOB_IDENT;