-- Query 1---
SELECT F_NAME, L_NAME FROM EMPLOYEES WHERE ADDRESS like '%Elgin,IL';
-- Query 2 --
SELECT F_NAME, L_NAME FROM EMPLOYEES WHERE B_DATE LIKE '197%';
-- QUERY 3---
SELECT F_NAME, L_NAME FROM EMPLOYEES WHERE DEP_ID=5 AND SALARY BETWEEN 60000 AND 70000;
-- QUERY 4A --
SELECT F_NAME, L_NAME,DEP_ID FROM EMPLOYEES ORDER BY DEP_ID;
-- QUERY 4B --
SELECT F_NAME, L_NAME, DEP_ID FROM EMPLOYEES ORDER BY DEP_ID, L_NAME DESC;
-- QUERY 5A--
SELECT DEP_ID, COUNT(DEP_ID) AS COUNT FROM EMPLOYEES GROUP BY DEP_ID;
-- QUERY 5B --
SELECT DEP_ID, COUNT(DEP_ID), AVG(SALARY) AS COUNT FROM EMPLOYEES GROUP BY DEP_ID;
--QUERY 5C --
SELECT DEP_ID, COUNT(DEP_ID) AS NUM_EMPLOYEES, AVG(SALARY) AS AVG_SALARY FROM EMPLOYEES GROUP BY DEP_ID;
--QUERY 5D --
SELECT DEP_ID, COUNT(DEP_ID) AS NUM_EMPLOYEES, AVG(SALARY) AS AVG_SALARY FROM EMPLOYEES GROUP BY DEP_ID ORDER BY AVG_SALARY;
--QUERY 5E--
SELECT DEP_ID, COUNT(DEP_ID) AS NUM_EMPLOYEES, AVG(SALARY) AS AVG_SALARY FROM EMPLOYEES GROUP BY DEP_ID HAVING COUNT(DEP_ID)<4 ORDER BY AVG_SALARY;
-- BONUS QUERY 6--
SELECT F_NAME, L_NAME, DEP_NAME FROM EMPLOYEES,DEPARTMENTS ORDER BY DEP_NAME,L_NAME DESC;
