-- PROBLEM 1--
SELECT * FROM EMPLOYEES WHERE SALARY<AVG(SALARY);
-- PROBLEM 2--
SELECT * FROM EMPLOYEES WHERE SALARY<(SELECT AVG(SALARY) FROM EMPLOYEES);
-- PROBLEM 3 --
SELECT EMP_ID, SALARY, MAX(SALARY) AS MAX_SALARY FROM EMPLOYEES;
-- PROBLEM 4 --
SELECT EMP_ID, SALARY, (SELECT MAX(SALARY) FROM EMPLOYEES) AS MAX_SALARY FROM EMPLOYEES;
-- PROBLEM 5 --
SELECT * FROM (SELECT EMP_ID, F_NAME, L_NAME, DEP_ID FROM EMPLOYEES) AS EMP4ALL;