--QUERY A1--
SELECT SUM(COST) FROM PETRESCUE;
--QUERY A1--
SELECT SUM(COST) AS SUM_OF_COST FROM PETRESCUE;
--QUERY A3--
SELECT MAX(QUANTITY) FROM PETRESCUE;
--QUERY A4--
SELECT AVG(COST) FROM PETRESCUE;
--QUERY A5--
SELECT AVG(COST/QUANTITY) FROM PETRESCUE WHERE ANIMAL='Dog';
--QUERY B1--
SELECT ROUND(COST) FROM PETRESCUE;
--QUERY B2--
SELECT ANIMAL,LENGTH(ANIMAL) FROM PETRESCUE;
--QUERY B3--
SELECT UCASE(ANIMAL) FROM PETRESCUE;
--QUERY B4--
SELECT DISTINCT(UCASE(ANIMAL)) FROM PETRESCUE;
--QUERY B5--
SELECT * FROM PETRESCUE WHERE LCASE(ANIMAL)='cat';
--QUERY C1--
SELECT DAY(RESCUEDATE) FROM PETRESCUE WHERE ANIMAL='Cat';
--QUERY C2--
SELECT SUM(QUANTITY) FROM PETRESCUE WHERE MONTH(RESCUEDATE)=5;
--QUERY C3--
SELECT SUM(QUANTITY) AS COUNT FROM PETRESCUE WHERE DAY(RESCUEDATE)=14;
--QUERY C4--
SELECT (RESCUEDATE+3 DAYS) FROM PETRESCUE; 
--QUERY C5--
SELECT DAY(CURRENT_DATE-RESCUEDATE) FROM PETRESCUE;