
SELECT TYPENAME, COLNAME, LENGTH FROM SYSCAT.COLUMNS WHERE TABNAME = 'CHICAGO_PUBLIC_SCHOOLS';
SELECT COUNT(*) FROM CHICAGO_PUBLIC_SCHOOLS WHERE "Elementary, Middle, or High School"='ES';
SELECT NAME_OF_SCHOOL FROM CHICAGO_PUBLIC_SCHOOLS WHERE SAFETY_SCORE=99;
SELECT NAME_OF_SCHOOL, AVERAGE_STUDENT_ATTENDANCE FROM CHICAGO_PUBLIC_SCHOOLS ORDER BY AVERAGE_STUDENT_ATTENDANCE DESC NULLS LAST LIMIT 10;
SELECT NAME_OF_SCHOOL, AVERAGE_STUDENT_ATTENDANCE FROM CHICAGO_PUBLIC_SCHOOLS ORDER BY AVERAGE_STUDENT_ATTENDANCE FETCH FIRST 5 ROWS ONLY;
SELECT NAME_OF_SCHOOL, REPLACE(AVERAGE_STUDENT_ATTENDANCE, '%','') AS AVERAGE_STUDENT_ATTENDANCE FROM CHICAGO_PUBLIC_SCHOOLS ORDER BY AVERAGE_STUDENT_ATTENDANCE FETCH FIRST 5 ROWS ONLY;
SELECT NAME_OF_SCHOOL, AVERAGE_STUDENT_ATTENDANCE FROM CHICAGO_PUBLIC_SCHOOLS WHERE CAST( REPLACE(AVERAGE_STUDENT_ATTENDANCE, '%','') AS DOUBLE)<70;
SELECT SUM(COLLEGE_ENROLLMENT), COMMUNITY_AREA_NAME FROM CHICAGO_PUBLIC_SCHOOLS GROUP BY COMMUNITY_AREA_NAME;
SELECT SUM(COLLEGE_ENROLLMENT), COMMUNITY_AREA_NAME FROM CHICAGO_PUBLIC_SCHOOLS GROUP BY COMMUNITY_AREA_NAME ORDER BY SUM(COLLEGE_ENROLLMENT) LIMIT 5;
SELECT SAFETY_SCORE, NAME_OF_SCHOOL FROM CHICAGO_PUBLIC_SCHOOLS ORDER BY SAFETY_SCORE LIMIT 5;
SELECT C.HARDSHIP_INDEX, S.COMMUNITY_AREA_NAME, S.COLLEGE_ENROLLMENT FROM CHICAGO_PUBLIC_SCHOOLS S, CENSUS_DATA C WHERE S.COLLEGE_ENROLLMENT=4368;
SELECT HARDSHIP_INDEX FROM CENSUS_DATA CD, CHICAGO_PUBLIC_SCHOOLS CPS WHERE CD.COMMUNITY_AREA_NUMBER = CPS.COMMUNITY_AREA_NUMBER AND COLLEGE_ENROLLMENT = (SELECT MAX(COLLEGE_ENROLLMENT) FROM CHICAGO_PUBLIC_SCHOOLS);

select COMMUNITY_AREA_NUMBER, COMMUNITY_AREA_NAME, HARDSHIP_INDEX FROM CENSUS_DATA 
   where COMMUNITY_AREA_NUMBER in 
   ( select COMMUNITY_AREA_NUMBER FROM CHICAGO_PUBLIC_SCHOOLS ORDER BY COLLEGE_ENROLLMENT DESC LIMIT 1 );