-- TASK 3 --
-- ALTER TABLE CHICAGO_CRIME_DATA RENAME COLUMN COLUMN_21 TO LOCATION;
-- PROBLEM 1 --
SELECT COUNT(ID) FROM CHICAGO_CRIME_DATA;
-- PROBLEM 2--
SELECT COMMUNITY_AREA_NAME, PER_CAPITA_INCOME FROM CENSUS_DATA WHERE PER_CAPITA_INCOME<11000;
-- PROBLEM 3 --
SELECT CASE_NUMBER FROM CHICAGO_CRIME_DATA WHERE DESCRIPTION LIKE '%MINOR';
-- PROBLEM 4 --
SELECT * FROM CHICAGO_CRIME_DATA WHERE PRIMARY_TYPE='KIDNAPPING';
-- PROBLEM 5 --
SELECT DISTINCT PRIMARY_TYPE FROM CHICAGO_CRIME_DATA WHERE LOCATION_DESCRIPTION LIKE 'SCHOOL%';
-- PROBLEM 6--
SELECT AVG(SAFETY_SCORE) FROM CHICAGO_PUBLIC_SCHOOLS;
-- PROBLEM 7--
SELECT COMMUNITY_AREA_NAME, PERCENT_HOUSEHOLDS_BELOW_POVERTY FROM CENSUS_DATA ORDER BY PERCENT_HOUSEHOLDS_BELOW_POVERTY DESC LIMIT 5;
-- PROBLEM 8 IS THE SAME AS 10 --
-- PROBLEM 9 --
SELECT COMMUNITY_AREA_NAME, HARDSHIP_INDEX FROM CENSUS_DATA ORDER BY HARDSHIP_INDEX DESC NULLS LAST LIMIT 1;
-- PROBLEM 10 --
SELECT COUNT(*) AS CRIME_COUNT, B.COMMUNITY_AREA_NAME FROM CHICAGO_CRIME_DATA A INNER JOIN CENSUS_DATA B ON A.COMMUNITY_AREA_NUMBER = B.COMMUNITY_AREA_NUMBER GROUP BY B.COMMUNITY_AREA_NAME ORDER BY CRIME_COUNT DESC LIMIT 1;
